language: go

go:
  - master

go_import_path: github.com/wangzitian0/golang-gin-starter-kit

services:
  - sqlite3

install:
  - mkdir -p src/github.com/wangzitian0/golang-gin-starter-kit
  - cp -r . src/github.com/wangzitian0/golang-gin-starter-kit
  - go get -u github.com/pilu/fresh
  - go get -u golang.org/x/crypto/...
  - go get -u github.com/kardianos/govendor
  - govendor sync
script:
#  - go test -v ./...
  - bash ./scripts/gofmt.sh
  - bash ./scripts/coverage.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)
