language: go

go:
  - 1.10
  - master

# go_import_path: github.com/wangzitian0/golang-gin-starter-kit

services:
  - sqlite3

install:
  - go get -d -v github.com/kardianos/govendor
  - go get -d -v github.com/pilu/fresh
  - go get -d -v golang.org/x/crypto/...
  - govendor sync
script:
#  - go test -v ./...
  - bash ./scripts/gofmt.sh
  - bash ./scripts/coverage.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)
